Repository prologuetechnology/tracking, pull requests merged in 2025-06, with the labels that each got.

#15 [SD2-43475] added seeder for roles and permission
  database/seeders/RolesAndPermissionsSeeder.php
Labels: size:M

#16 [SD2-43477] adding menu option for user managment
  resources/js/components/feature/user/navigation/UserDropdown.vue
Labels: size:XS

#18 SD2-43480:
  app/Http/Middleware/HandleInertiaRequests.php
  app/Models/User.php
  bootstrap/app.php
  resources/js/components/feature/company/CompanyCreateButton.vue
  resources/js/composables/hooks/auth/index.js
  resources/js/composables/hooks/auth/useHasPermissions.js
  routes/web.php
Labels: size:M

#20 [SD2-43536] Added mutation for roles and permissions
  app/Http/Controllers/Api/PermissionController.php
  app/Http/Controllers/Api/RoleController.php
  app/Http/Requests/AssignRolePermissionsRequest.php
  app/Http/Requests/StoreUserRolesRequest.php
  app/Http/Requests/UpdateRoleRequest.php
  resources/js/composables/mutations/userRoles/useUserRolesAssignPermissionsMutation.js
  resources/js/composables/mutations/userRoles/useUserRolesCreateMutation.js
  resources/js/composables/mutations/userRoles/useUserRolesDeleteMutation.js
  resources/js/composables/mutations/userRoles/useUserRolesUpdateMutation.js
  routes/api.php
Labels: size:L

#19 [SD2-43484] creating a table view for users to assign roles
  resources/js/components/feature/userManagement/UserManagementTable.vue
  resources/js/components/feature/userManagement/UserRolesDropdown.vue
  resources/js/composables/queries/roles/index.js
  resources/js/composables/queries/roles/useRolesQuery.js
  resources/js/pages/admin/Dashboard.vue
  resources/js/pages/admin/userManagement/Edit.vue
  routes/web.php
Labels: size:L

#28 [SD2-43578] implement CRUD operations for permissions and update routes
  app/Http/Controllers/Api/PermissionController.php
  resources/js/components/feature/permission/PermissionCreateButton.vue
  resources/js/components/feature/permission/PermissionDestroyDialog.vue
  resources/js/components/feature/permission/PermissionForm.vue
  resources/js/components/feature/permission/PermissionInfoCell.vue
  resources/js/components/feature/permission/PermissionSetImageAsset.vue
  resources/js/components/feature/permission/PermissionUpdateButton.vue
  resources/js/components/feature/permission/PermissionsDataTable.vue
  resources/js/components/feature/permission/ToggleCompanyIsActive.vue
  resources/js/components/feature/permission/ToggleMapSwitch.vue
  resources/js/components/layout/navigation/AuthenticatedNavbar.vue
  resources/js/composables/mutations/permission/index.js
  resources/js/composables/mutations/permission/usePermissionCreateMutation.js
  resources/js/composables/mutations/permission/usePermissionDestroyMutation.js
  resources/js/composables/mutations/permission/usePermissionSetImageAssetMutation.js
  resources/js/composables/mutations/permission/usePermissionThemeMutation.js
  resources/js/composables/mutations/permission/usePermissionUpdateMutation.js
  resources/js/composables/queries/permission/index.js
  resources/js/composables/queries/permission/usePermissionQuery.js
  resources/js/composables/queries/permission/usePermissionsQuery.js
  resources/js/pages/admin/permissions/Create.vue
  resources/js/pages/admin/permissions/Edit.vue
  resources/js/pages/admin/permissions/Index.vue
  routes/api.php
  routes/web.php
Labels: size:XXL

#27 Sd2 43562
  resources/js/components/feature/company/CompaniesDataTable.vue
  resources/js/components/feature/company/CompanyDestroyDialog.vue
  resources/js/components/feature/company/CompanyInfoCell.vue
  resources/js/components/feature/theme/ThemeCreateButton.vue
  resources/js/components/feature/theme/ThemeDestroyDialog.vue
  resources/js/components/feature/userManagement/UserManagementTable.vue
  resources/js/components/layout/navigation/AuthenticatedNavbar.vue
  resources/js/pages/admin/theme/Index.vue
Labels: size:M
